name = "endel-estudios-api"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "endel-estudios-db"
database_id = "7d0d9674-eb16-4a53-8719-5fe632d031fa"

[[kv_namespaces]]
binding = "STORAGE"
id = "8727a686d74d40b18813ddccfc1588af"

[vars]
ADMIN_PASSWORD = "endel47362512026"